version: '3.7'

services:
  apisix:
    image: apache/apisix:3.11.0-debian
    volumes:
      - ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080"  # HTTP port
      - "9443:9443"  # HTTPS port
    environment:
      - GATEWAY_PORT=9080
    depends_on:
      - opa
      # - web

  opa:
    image: openpolicyagent/opa:latest
    volumes:
      - ./conf/policy.rego:/policy.rego:ro
    command: ["run", "--server", "--log-level=debug", "/policy.rego"]
    ports:
      - "8181:8181"

  backend:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/backend.conf:/etc/nginx/nginx.conf
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80